### ISSUE TITLE
Unable to parse response

### ISSUE THREAD

**Issue by howudodat** [Piwigo/Piwigo-Java#2]
First time syncing an album worked, tried again and I get these errors:

java -jar remotesync-ui.jar -debug
08:59:10.213 [main] DEBUG o.piwigo.remotesync.api.AbstractMain - Debug is enabled
08:59:10.216 [main] DEBUG o.p.r.api.conf.ConfigurationUtil - found userConfig file /home/peter/.config/piwigo/remotesync
08:59:10.296 [main] DEBUG o.p.r.api.conf.ConfigurationUtil - configuration loaded
08:59:10.379 [AWT-EventQueue-0] DEBUG o.p.remotesync.ui.swing.RemotesyncUI - Initialize RemotesyncUI window
08:59:10.535 [AWT-EventQueue-0] DEBUG o.p.remotesync.ui.swing.RemotesyncUI - RemotesyncUI window initialized
08:59:10.645 [AWT-EventQueue-0] DEBUG o.p.remotesync.ui.swing.RemotesyncUI - RemotesyncUI window created
08:59:12.896 [AWT-EventQueue-0] DEBUG o.p.remotesync.ui.swing.RemotesyncUI - RemotesyncUI sync button pressed
08:59:12.900 [AWT-EventQueue-0] DEBUG o.p.remotesync.ui.swing.RemotesyncUI - RemotesyncUI sync button action finished
08:59:12.901 [Thread-0] DEBUG org.piwigo.remotesync.api.Job - running false
08:59:12.904 [Thread-0] INFO  o.piwigo.remotesync.api.sync.SyncJob - User peter will sync gallery http://www.earthbest.com/photos with directory /home/peter/Pictures/E H Albums
08:59:12.922 [Thread-0] DEBUG o.p.remotesync.api.cache.LegacyCache - /home/peter/Pictures/E H Albums/.piwigo_import_tree.txt doesn't exist
08:59:12.955 [Thread-0] DEBUG o.p.r.api.sync.SyncDirectoryWalker - album already in cache : /home/peter/Pictures/E H Albums/2
08:59:12.970 [Thread-0] DEBUG o.p.r.api.sync.SyncDirectoryWalker - image already in cache : /home/peter/Pictures/E H Albums/2/002d.jpg
08:59:12.971 [Thread-0] DEBUG o.p.r.api.sync.SyncDirectoryWalker - image already in cache : /home/peter/Pictures/E H Albums/2/002c.jpg
08:59:12.974 [Thread-0] DEBUG o.p.r.api.sync.SyncDirectoryWalker - image already in cache : /home/peter/Pictures/E H Albums/2/004a.jpg
08:59:12.975 [Thread-0] DEBUG o.p.r.api.sync.SyncDirectoryWalker - image already in cache : /home/peter/Pictures/E H Albums/2/2-009.jpg
08:59:12.980 [Thread-0] INFO  o.p.r.api.sync.SyncDirectoryWalker - will upload image for /home/peter/Pictures/E H Albums/2/00.JPG in album with id 5
08:59:12.982 [Thread-0] INFO  o.p.r.api.sync.ConnectedWalker - Connecting... 
08:59:13.375 [Thread-0] INFO  o.p.r.api.sync.ConnectedWalker - Connect successful
08:59:13.444 [Thread-0] DEBUG o.p.remotesync.api.client.WSClient - XmlContent : <br />
<b>Warning</b>:  md5_file(): Filename cannot be empty in <b>/var/www/earthbest.com/htdocs/photos/admin/include/functions_upload.inc.php</b> on line <b>170</b><br />
<br />
<b>Warning</b>:  getimagesize(): Filename cannot be empty in <b>/var/www/earthbest.com/htdocs/photos/admin/include/functions_upload.inc.php</b> on line <b>221</b><br />
forbidden file type
08:59:13.447 [Thread-0] DEBUG o.p.remotesync.api.client.WSClient - Class : org.piwigo.remotesync.api.response.ServerResponse 
08:59:13.458 [Thread-0] ERROR o.p.remotesync.api.client.WSClient - Unable to parse response
org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.Attribute(name=stat, required=true, empty=) on field 'status' public java.lang.String org.piwigo.remotesync.api.response.BasicResponse.status for class org.piwigo.remotesync.api.response.ServerResponse at line 1
    at org.simpleframework.xml.core.Composite.validate(Composite.java:644) ~[remotesync-ui.jar:0.0.12]
    at org.simpleframework.xml.core.Composite.readAttributes(Composite.java:416) ~[remotesync-ui.jar:0.0.12]
    at org.simpleframework.xml.core.Composite.access$300(Composite.java:59) ~[remotesync-ui.jar:0.0.12]
    at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1382) ~[remotesync-ui.jar:0.0.12]
    at org.simpleframework.xml.core.Composite.read(Composite.java:201) ~[remotesync-ui.jar:0.0.12]
    at org.simpleframework.xml.core.Composite.read(Composite.java:148) ~[remotesync-ui.jar:0.0.12]
    at org.simpleframework.xml.core.Traverser.read(Traverser.java:92) ~[remotesync-ui.jar:0.0.12]
    at org.simpleframework.xml.core.Persister.read(Persister.java:625) ~[remotesync-ui.jar:0.0.12]
    at org.simpleframework.xml.core.Persister.read(Persister.java:606) ~[remotesync-ui.jar:0.0.12]
    at org.simpleframework.xml.core.Persister.read(Persister.java:584) ~[remotesync-ui.jar:0.0.12]
    at org.simpleframework.xml.core.Persister.read(Persister.java:562) ~[remotesync-ui.jar:0.0.12]
    at org.simpleframework.xml.core.Persister.read(Persister.java:499) ~[remotesync-ui.jar:0.0.12]
    at org.piwigo.remotesync.api.client.WSClient.parseResponse(WSClient.java:204) [remotesync-ui.jar:0.0.12]
    at org.piwigo.remotesync.api.client.WSClient.doSendRequest(WSClient.java:96) [remotesync-ui.jar:0.0.12]
    at org.piwigo.remotesync.api.client.AbstractClient.sendRequest(AbstractClient.java:26) [remotesync-ui.jar:0.0.12]
    at org.piwigo.remotesync.api.client.WSClient.sendRequest(WSClient.java:75) [remotesync-ui.jar:0.0.12]
    at org.piwigo.remotesync.api.sync.ConnectedWalker.createImage(ConnectedWalker.java:97) [remotesync-ui.jar:0.0.12]
    at org.piwigo.remotesync.api.sync.SyncDirectoryWalker.handleFile(SyncDirectoryWalker.java:76) [remotesync-ui.jar:0.0.12]
    at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:367) [remotesync-ui.jar:0.0.12]
    at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364) [remotesync-ui.jar:0.0.12]
    at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:335) [remotesync-ui.jar:0.0.12]
    at org.piwigo.remotesync.api.sync.SyncDirectoryWalker.walk(SyncDirectoryWalker.java:81) [remotesync-ui.jar:0.0.12]
    at org.piwigo.remotesync.api.sync.SyncJob.doExecute(SyncJob.java:34) [remotesync-ui.jar:0.0.12]
    at org.piwigo.remotesync.api.Job.execute(Job.java:30) [remotesync-ui.jar:0.0.12]
    at org.piwigo.remotesync.api.Job$1.run(Job.java:42) [remotesync-ui.jar:0.0.12]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
08:59:13.460 [Thread-0] ERROR o.p.r.api.sync.ConnectedWalker - Cannot updload image for /home/peter/Pictures/E H Albums/2/00.JPG

**Comment by mhelleboid** [comment]
I'm not able to reproduce this bug. Is there anything special about the 00.JPG file?
Which versions of remote-sync and piwigo are you using?

**Comment by JimboJoe** [comment]
Hi,
I  get the same error outputs with remote-sync 0.0.13 and Piwigo 2.8.5.
I can see that the images files have been copied on the Piwigo server, but no metadata has been created inside Piwigo (i.e. no album created).

**Comment by Valou447** [comment]
Hello @howudodat and @JimboJoe,

I checked out both of your errors, everything should be fix by now.
Please note that Piwigo > 2.9 is now required for using Piwigo Remote Sync.

The version 0.0.14 is out, so don't hesitate to take a look on the release page !

Thank you !
