### ISSUE TITLE
I can't connect to my piwigo instance

### ISSUE THREAD

**Issue by Clemorange22** [Piwigo/Piwigo-Java#20]
When I try to connect to my piwigo , an invalid credentials error message is displayed, even if it's the good credentials
Note : I'm using LDAP and it's works fine on webui
![image](https://user-images.githubusercontent.com/62897760/129712179-a79b212a-cccf-46e1-b4dd-1ca88066bf06.png)

**Comment by celogeek** [comment]
I've got the same issue (using normal credential).
I use php8, piwigo 12

Here the problem:
```
Nov 25 20:32:04 piwigo php-fpm[397]: pool www[397]: PHP Fatal error:  Uncaught TypeError: get_class(): Argument #1 ($object) must be of type object, bool given in /app/include/ws_protocols/rest_encoder.php:145
Nov 25 20:32:04 piwigo php-fpm[397]: pool www[397]: Stack trace:
Nov 25 20:32:04 piwigo php-fpm[397]: pool www[397]: #0 /app/include/ws_core.inc.php(289): PwgRestEncoder->encodeResponse()
Nov 25 20:32:04 piwigo php-fpm[397]: pool www[397]: #1 /app/include/ws_protocols/rest_handler.php(42): PwgServer->sendResponse()
Nov 25 20:32:04 piwigo php-fpm[397]: pool www[397]: #2 /app/include/ws_core.inc.php(281): PwgRestRequestHandler->handleRequest()
Nov 25 20:32:04 piwigo php-fpm[397]: pool www[397]: #3 /app/ws.php(22): PwgServer->run()
Nov 25 20:32:04 piwigo php-fpm[397]: pool www[397]: #4 {main}
Nov 25 20:32:04 piwigo php-fpm[397]: pool www[397]:   thrown in /app/include/ws_protocols/rest_encoder.php on line 145
```
