### ISSUE TITLE
remotesync-ui not working

### ISSUE THREAD

**Issue by H0tamer** [Piwigo/Piwigo-Java#25]
Problem exists since approximately 9th December 2023.
Currently I have the latest version of Piwigo, 14.1.0, installed.

00:25:02.475 [Thread-1] DEBUG o.p.remotesync.api.client.WSClient - Class : org.piwigo.remotesync.api.response.PwgSessionGetStatusResponse 
00:25:02.476 [Thread-1] ERROR o.p.remotesync.api.client.WSClient - Unable to parse response
org.simpleframework.xml.core.ElementException: Element 'save_visits' does not have a match in class org.piwigo.remotesync.api.response.PwgSessionGetStatusResponse at line 3
	at org.simpleframework.xml.core.Composite.readElement(Composite.java:527) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Composite.readElements(Composite.java:445) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Composite.access$400(Composite.java:59) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Composite.read(Composite.java:201) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Composite.read(Composite.java:148) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Traverser.read(Traverser.java:92) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Persister.read(Persister.java:625) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Persister.read(Persister.java:606) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Persister.read(Persister.java:584) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Persister.read(Persister.java:562) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Persister.read(Persister.java:499) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.client.WSClient.parseResponse(WSClient.java:232) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.client.WSClient.doSendRequest(WSClient.java:104) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.client.AuthenticatedWSClient.getSessionStatus(AuthenticatedWSClient.java:63) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.client.AuthenticatedWSClient.checkRequestAuthorization(AuthenticatedWSClient.java:47) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.client.WSClient.doSendRequest(WSClient.java:95) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.client.AbstractClient.sendRequest(AbstractClient.java:26) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.client.WSClient.sendRequest(WSClient.java:79) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.sync.ConnectedWalker.createImage(ConnectedWalker.java:114) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.sync.SyncDirectoryWalker.handleFile(SyncDirectoryWalker.java:75) ~[remotesync-ui.jar:1.0]
	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:367) ~[remotesync-ui.jar:1.0]
	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364) ~[remotesync-ui.jar:1.0]
	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:335) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.sync.SyncDirectoryWalker.walk(SyncDirectoryWalker.java:81) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.sync.SyncJob.doExecute(SyncJob.java:43) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.Job.execute(Job.java:28) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.Job$1.run(Job.java:39) ~[remotesync-ui.jar:1.0]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
00:25:02.476 [Thread-1] ERROR o.p.r.api.sync.ConnectedWalker - Cannot upload image for C:\Users\jos\OneDrive\Bilder\H0tamer\Benutzt\H0tamer_20231211.jpg
org.piwigo.remotesync.api.exception.ClientException: Unable to parse response
	at org.piwigo.remotesync.api.client.WSClient.parseResponse(WSClient.java:238) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.client.WSClient.doSendRequest(WSClient.java:104) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.client.AuthenticatedWSClient.getSessionStatus(AuthenticatedWSClient.java:63) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.client.AuthenticatedWSClient.checkRequestAuthorization(AuthenticatedWSClient.java:47) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.client.WSClient.doSendRequest(WSClient.java:95) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.client.AbstractClient.sendRequest(AbstractClient.java:26) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.client.WSClient.sendRequest(WSClient.java:79) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.sync.ConnectedWalker.createImage(ConnectedWalker.java:114) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.sync.SyncDirectoryWalker.handleFile(SyncDirectoryWalker.java:75) ~[remotesync-ui.jar:1.0]
	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:367) ~[remotesync-ui.jar:1.0]
	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:364) ~[remotesync-ui.jar:1.0]
	at org.apache.commons.io.DirectoryWalker.walk(DirectoryWalker.java:335) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.sync.SyncDirectoryWalker.walk(SyncDirectoryWalker.java:81) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.sync.SyncJob.doExecute(SyncJob.java:43) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.Job.execute(Job.java:28) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.Job$1.run(Job.java:39) ~[remotesync-ui.jar:1.0]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: org.simpleframework.xml.core.ElementException: Element 'save_visits' does not have a match in class org.piwigo.remotesync.api.response.PwgSessionGetStatusResponse at line 3
	at org.simpleframework.xml.core.Composite.readElement(Composite.java:527) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Composite.readElements(Composite.java:445) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Composite.access$400(Composite.java:59) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Composite$Builder.read(Composite.java:1383) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Composite.read(Composite.java:201) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Composite.read(Composite.java:148) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Traverser.read(Traverser.java:92) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Persister.read(Persister.java:625) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Persister.read(Persister.java:606) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Persister.read(Persister.java:584) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Persister.read(Persister.java:562) ~[remotesync-ui.jar:1.0]
	at org.simpleframework.xml.core.Persister.read(Persister.java:499) ~[remotesync-ui.jar:1.0]
	at org.piwigo.remotesync.api.client.WSClient.parseResponse(WSClient.java:232) ~[remotesync-ui.jar:1.0]
	... 16 common frames omitted

**Comment by macstrat** [comment]
Im Having the Same issue on version 14.1.0 Error for multiple files is:
14:53:45.789 [Thread-5] INFO  o.p.r.api.sync.SyncDirectoryWalker - Uploading Yokai_0039.jpeg in album with ID null
14:53:45.789 [Thread-5] ERROR o.p.r.api.sync.ConnectedWalker - Cannot upload an image without an album. Please move the image in a subfolder.

**Comment by plegall** [comment]
The problem is that API method `pwg.session.getStatus` has been updated in Piwigo 14 to output a new information `save_vists`. It breaks the Java code in Piwigo Remote Sync :-/ In Piwigo 14.3.0, Piwigo `pwg.session.getStatus` makes a test : if the call is from PiwigoRemoteSync, do not send the new `save_visits` info.

That is clearly temporary patch and I keep this issue opened before it's correctly fixed.

**Comment by datwildfire** [comment]
> The problem is that API method `pwg.session.getStatus` has been updated in Piwigo 14 to output a new information `save_vists`. It breaks the Java code in Piwigo Remote Sync :-/ In Piwigo 14.3.0, Piwigo `pwg.session.getStatus` makes a test : if the call is from PiwigoRemoteSync, do not send the new `save_visits` info.
> 
> That is clearly temporary patch and I keep this issue opened before it's correctly fixed.

Any fix available?
